{% set name = "gotran" %}
{% set version = "2023.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: df1d843fd43b6037f99b1b3564d553e7ee019b918d6a24e128515490f89dc345

build:
  number: 0
  noarch: python
  entry_points:
    - "gotran=gotran.__main__:main"
    - "cellml2gotran=gotran.scripts.cellml2gotran:main"
    - "gotran2c=gotran.scripts.gotran2c:main"
    - "gotran2cpp=gotran.scripts.gotran2cpp:main"
    - "gotran2dolfin=gotran.scripts.gotran2dolfin:main"
    - "gotran2julia=gotran.scripts.gotran2julia:main"
    - "gotran2latex=gotran.scripts.gotran2latex:main"
    - "gotran2matlab=gotran.scripts.gotran2matlab:main"
    - "gotran2opencl=gotran.scripts.gotran2opencl:main"
    - "gotran2py=gotran.scripts.gotran2py:main"
    - "gotranexport=gotran.scripts.gotranexport:main"
    - "gotranrun=gotran.scripts.gotranrun:main"
    - "gotran2md=gotran.scripts.gotran2md:main"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - modelparameters
    - numpy
    - scipy
    - networkx
    - packaging

test:
  imports:
    - gotran

  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/ComputationalPhysiology/gotran
  summary: Library for declaring and translating ODEs
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/gotran/
  dev_url: https://github.com/ComputationalPhysiology/gotran

extra:
  recipe-maintainers:
    - finsberg
